// README bundled with the downloaded guide
export function generateReadme(d) {
  const name = d.propertyName || 'Welcome Guide';
  return `# ${name} — Digital Welcome Guide

A static HTML guide for your guests. No backend, no build step — open and deploy.

## File Structure

\`\`\`
${name.toLowerCase().replace(/\\s+/g, '-')}/
├── index.html        ← Main page
├── css/style.css     ← All styles
├── js/main.js        ← Interactions
└── images/           ← Your photos
\`\`\`

## Preview Locally

Open \`index.html\` in any browser, or run a local server:

\`\`\`bash
npx serve -p 3000 .
\`\`\`

Then visit http://localhost:3000

## Deploy to Netlify (Drag & Drop)

1. Go to https://app.netlify.com/drop
2. Drag this entire folder onto the page
3. Done — your guide is live!

## Deploy to Vercel

\`\`\`bash
npm install -g vercel
vercel --prod
\`\`\`

## Edit Content Later

You can edit the \`index.html\` file directly to update any text. The CSS is in \`css/style.css\` and contains color variables at the top — change those to retheme the whole guide.

---

Generated by **Digital Welcome Guide Builder**
`;
}
